version: "3"

services:
  backend:
    build: ./backend
    volumes:
      - data:/code/db
    ports:
      - "3080:8000"

  front:
    build: ./front
    ports: 
      - "8080:8080"

volumes: 
  data:
