version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports: 
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:6.2.5-alpine
    ports: 
      - 6379:6379

  backend:
    build: ./backend
    volumes:
      - data:/code/db
    ports:
      - "8001:8000"
    depends_on:
        - rabbitmq
        - consumer
    environment:
      RABBITMQ_SERVER: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      RABBITMQ_QUEUE: send_email
      REDIS_SERVER: redis

  consumer:
    build: ./consumer

    environment:
      RABBITMQ_SERVER: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      RABBITMQ_QUEUE: send_email
      DEFAULT_FROM_EMAIL: hiTSJ5V7@protonmail.com
      SENDGRID_API_KEY: 
    
    depends_on:
      - rabbitmq


volumes: 
  data:
